compile:

	python -m numpy.f2py -c -m akkff akk_ff.f

	python -m numpy.f2py -c -m dss_14_k fDSSK.f

	python -m numpy.f2py -c -m dss_07_k fDSSK_old.f

	python -m numpy.f2py -c -m dss_07_pi fDSSPI_old.f

	python -m numpy.f2py -c -m dss_14_pi fDSSPI.f

	python -m numpy.f2py -c -m dss_pi fDSS_pi.f

	python -m numpy.f2py -c -m dss_k fDSS_k.f


